package:
  name: libqglviewer
  version: 2.6.4

source:
  git_url: https://github.com/GillesDebunne/libQGLViewer
  git_tag: v2.6.4
  patches:
   # List any patch files here
   - QGLViewer_pro.patch
   - examples.pri.patch
   - libQGLViewer.pro.patch

build:
  number: 2


requirements:
  build:
      - m2-patch                           # [win]
      - patch                              # [unix]
      - {{ compiler('cxx') }}
      - make                               # [unix]
  host:
      - qt 
      - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
      - {{ cdt('libx11-devel') }}          # [linux]
      - {{ cdt('libxext-devel') }}         # [linux]
      - {{ cdt('libxrender-devel') }}      # [linux]
      - {{ cdt('mesa-libgl-devel') }}      # [linux]
      - {{ cdt('mesa-libegl-devel') }}     # [linux]
      - {{ cdt('mesa-dri-drivers') }}      # [linux]
      - {{ cdt('libxdamage') }}            # [linux]
      - {{ cdt('libxdamage-devel') }}      # [linux]
      - {{ cdt('libxfixes') }}             # [linux]
      - {{ cdt('libxfixes-devel') }}       # [linux]
      - {{ cdt('libxxf86vm') }}            # [linux]
      - {{ cdt('libxxf86vm-devel') }}      # [linux]
      - {{ cdt('libselinux-devel') }}      # [linux]
      - {{ cdt('libselinux-devel') }}      # [linux]
      - libglu                             # [linux]
  run:
    - qt

about:
  home: http://www.libqglviewer.com
  license: GPL
  summary: libQGLViewer is a C++ library based on Qt that eases the creation of OpenGL 3D viewers.
