package:
  name: libqglviewer
  version: 2.7.2

source:
  git_url: https://github.com/GillesDebunne/libQGLViewer
  git_tag: v2.7.2
  patches:
   # List any patch files here
   - QGLViewer_pro.patch
   #- examples.pri.patch
   #- libQGLViewer.pro.patch

build:
  number: 0


requirements:
  build:
      - m2-patch                           # [win]
      - patch                              # [unix]
      - {{ compiler('cxx') }}
      - make                               # [unix]
  host:
      - qt 
      - {{ cdt('mesa-libgl-devel') }}      # [linux]
      - {{ cdt('mesa-dri-drivers') }}      # [linux]
      - {{ cdt('libselinux') }}            # [linux]
      - {{ cdt('libxdamage') }}            # [linux]
      - {{ cdt('libxxf86vm') }}            # [linux]
      - libglu                             # [linux]
  run:
      - qt
      - xorg-libxfixes  # [linux]
      - libglu                             # [linux]
about:
  home: http://www.libqglviewer.com
  license: GPL
  summary: libQGLViewer is a C++ library based on Qt that eases the creation of OpenGL 3D viewers.
